### ISSUE TITLE
Unusual elm-version

### ISSUE THREAD

**Issue by MartinSStewart** [IzumiSy/elm-multi-waitable#1]
Hi, I noticed in your elm.json you have `"elm-version": "0.18.0 <= v < 0.20.0"`. I don't think that's a valid dependency range. It should probably be `"elm-version": "0.19.0 <= v < 0.20.0"` instead.

**Comment by IzumiSy** [comment]
Right. I will fix that.

**Comment by IzumiSy** [comment]
Fix that and published.
